stages:
  - dependencies
  - build
  - test

opencv-build:
  stage: dependencies
  script:
    - sudo apt-get install build-essential
    - sudo apt-get install cmake cmake-qt-gui git pkg-config libgtk2.0-dev libavcodec-dev libavformat-dev libswscale-dev
    - export I3D_OPENCV_VERSION=2.4.13
    - wget --quiet https://github.com/opencv/opencv/archive/$I3D_OPENCV_VERSION.tar.gz
    - mkdir opencv-source opencv-build opencv-install
    - tar -xfz $I3D_OPENCV_VERSION.tar.gz -C opencv-source --strip-components=1
    - cmake -Bopencv-build -Hopencv-source -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_DOCS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_JPEG=ON -DBUILD_PNG=ON -DBUILD_TIFF=ON -DBUILD_opencv_gpu=OFF -DWITH_FFMPEG=OFF
    - make -j$(nproc) -C opencv-build
    - make -C opencv-build install DESTDIR=../opencv-install
    - bash .gitlab_build_files/build_opencv_debian_pkg.sh
  artifacts:
    paths:
      - i3d-opencv_*_amd64.deb
  tags:
    - linux

test-build:
  stage: build
  script:
    # run the tests..
    - make test
  tags:
    - linux
    
runtest:
  stage: test
  script:
    - bin/test
  tags:
    - linux